Actividades/Actividad7/Actividad7/Models/Employee.cs
namespace Actividad7.Models
{
    public class Employee :Entity
    {
        public string Identification { get; private set; }

        public string Name { get; private set; }

        public DateTime FechaDeIngreso { get; private set; }

        public int EnterpriseId { get; private set; }

        public Enterprise Enterprise { get; private set; }

        /// <summary>
        /// for
        /// </summary>
        public Employee() :base()
        {

        }

        private Employee(int id, string identification, string name, DateTime fechaDeIngreso, int enterpriseId) : base(id)
        {
            Identification = identification;
            Name = name;
            FechaDeIngreso = fechaDeIngreso;
            EnterpriseId = enterpriseId;
        }

        public static Employee Build(int id, string identification, string name, 
            DateTime fechaDeIngreso, int enterpriseId)
        {
            return new Employee(id, identification, name, fechaDeIngreso, enterpriseId);
        }
    }
}

Actividades/Actividad7/Actividad7/Models/Enterprise.cs
namespace Actividad7.Models
{
    public class Enterprise :Entity
    {
        public string Nit { get; private set; }

        public string Name { get; private set; }

        public string Direccion { get; private set; }

        public List<Employee> Employees { get; private set; }

        /// <summary>
        /// for
        /// </summary>
        private Enterprise() : base()
        {

        }

        private Enterprise(int id, string nit, string name, string direccion):base(id)
        {
            Nit = nit;
            Name = name;
            Direccion = direccion;
            Employees = new();
        }

        public static Enterprise Build(int id, string nit, string name, string direccion)
        {
            return new Enterprise(id, nit, name, direccion);
        }

        public void AddEmployees(Employee employee)
        {
            this.Employees.Add(employee);
        }
    }
}

Actividades/Actividad7/Actividad7/Models/Entity.cs
namespace Actividad7.Models
{
    public abstract class Entity
    {
        public int Id { get; protected set; }

        /// <summary>
        /// for
        /// </summary>
        protected Entity()
        {

        }

        protected Entity(int id)
        {
            Id = id;
        }

    }
}

Actividades/Actividad7/Actividad7/Models/ErrorViewModel.cs
namespace Actividad7.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Actividades/Actividad7/Actividad7/Controllers/EmployeeController.cs
using Actividad7.Models;
using Actividad7.Services;
using Microsoft.AspNetCore.Mvc;

namespace Actividad7.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly EmployeeService employeeServicee;

        public EmployeeController(EmployeeService employeeServicee)
        {
            this.employeeServicee = employeeServicee;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var employees = await employeeServicee.GetAllEmployees();
            return View(employees);
        }

        [HttpPost]
        public async Task<IActionResult> Create(int id,string identification, string name, DateTime fechaDeIngreso, int enterpriseId)
        {
            var employee = Employee.Build(id, identification, name , fechaDeIngreso, enterpriseId);
            await this.employeeServicee.Create(employee);
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPut]
        public async Task<IActionResult> Update(int id, string identification, string name, DateTime fechaDeIngreso, int enterpriseId)
        {
            var employee = Employee.Build(id, identification, name, fechaDeIngreso, enterpriseId);
            await this.employeeServicee.Update(employee);
            return View();
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id, string identification, string name, DateTime fechaDeIngreso, int enterpriseId)
        {
            var employee = Employee.Build(id, identification, name, fechaDeIngreso, enterpriseId);
            await this.employeeServicee.Delete(employee);
            return View();
        }
    }
}

Actividades/Actividad7/Actividad7/Controllers/EnterpriseController.cs
using Actividad7.Models;
using Actividad7.Services;
using Microsoft.AspNetCore.Mvc;

namespace Actividad7.Controllers
{
    public class EnterpriseController : Controller
    {
        private readonly EnterpriseService enterpriseService;

        public EnterpriseController(EnterpriseService enterpriseService)
        {
            this.enterpriseService = enterpriseService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var enterprises = await enterpriseService.GetAllEnterprises();
            return View(enterprises);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var enterprise = await enterpriseService.GetById(id);
            return View(enterprise);
        }

        [HttpPost]
        public async Task<IActionResult> Create(int id,string nit, string name, string direccion)
        {
            if (ModelState.IsValid)
            {
                var enterprise = Enterprise.Build(id, nit, name, direccion);
                await this.enterpriseService.Create(enterprise);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, string nit, string name, string direccion)
        {
            if (ModelState.IsValid)
            {
                var enterprise = Enterprise.Build(id, nit, name, direccion);
                await this.enterpriseService.Update(enterprise);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var consulta = await enterpriseService.GetById(id);
           // var enterprise = Enterprise.Build(id, consulta.Nit, consulta.Name, consulta.Direccion);
            await this.enterpriseService.Delete(consulta);
            return Content("1");
        }
    }
}

Actividades/Actividad7/Actividad7/Controllers/HomeController.cs
using Actividad7.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Actividad7.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Actividades/Actividad7/Actividad7/Views/Enterprise/Create.cshtml
@using Actividad7.Models;
@model Enterprise
@{
    ViewData["title"] = "CrearEnterprise";
}
<div class="form-row">
    <div class="col-md-12">
        <form method="post" asp-controller="Enterprise" class="form-group">
          <!--Nit-->
          <div class="mb-3">
            <label asp-for="Nit" class="form-label">Nit</label>
            <input asp-for="Nit" type="text" class="form-control" />
            <span asp-validation-for="Nit" class="text-danger"></span>
          </div>

          <!--Nombre-->
          <div class="mb-3">
            <label asp-for="Name" class="form-label">Nombre</label>
            <input asp-for="Name" type="text" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
          </div>

          <!--Direccion-->
          <div class="mb-3">
            <label asp-for="Direccion" class="form-label">Direccion</label>
            <input asp-for="Direccion" type="text" class="form-control" />
            <span asp-validation-for="Direccion" class="text-danger"></span>
          </div>

          <div class="container">
            <div class="col-sm">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
          </div>
      </form>
    </div>
</div>

Actividades/Actividad7/Actividad7/Views/Enterprise/Index.cshtml
@using Actividad7.Models;
@model List<Enterprise>

@{
    ViewData["title"] = "Index";
}

<div class="col-sm-6">
    <a class="btn btn-primary" asp-area="" asp-controller="Enterprise" asp-action="Create">Crear empresa</a>
</div>

    @if(Model.Count != 0)
    {
        <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Nit</th>
          <th scope="col">Nombre</th>
          <th scope="col">Direccion</th>
        </tr>
      </thead>
      <tbody>
          @foreach(var e in Model)
          {
            <tr>
              <td>@e.Id</td>
              <td>@e.Nit</td>
              <td>@e.Name</td>
              <td>@e.Direccion</td>
              <td>
                  <a asp-route-id= "@e.Id" asp-action="Update" 
                  class="btn btn-success btnsm">Editar</a>

                  <input onclick="jsDelete(@e.Id);" type="button" value="Eliminar" class="btn btn-danger" />
              </td>
            </tr>
            }
      </tbody>
    </table>
    }
    else{
        <div class="card">
              <div class="card-body">
                No hay datos.
              </div>
        </div>
    }


<script>
    function jsDelete(id) {
        if (confirm("Esta seguro de borrar la empresa?")) {
            url = "@Url.Content("~/Enterprise/Delete")" + "/" + id;

            $.post(url, function(data) {

                if (data == "1") {
                    document.location.href="@Url.Content("~/Enterprise/")"
                } else {
                    alert("Ocurrio un error")
                }

            })
        }
        
    }
</script>

Actividades/Actividad7/Actividad7/Views/Enterprise/Update.cshtml
@using Actividad7.Models;
@model Enterprise

@{
    ViewData["title"] = "Update";
}
<div class="form-row">
    <div class="col-md-12">
        <form method="post" asp-controller="Enterprise" class="form-group">

          <input type="hidden" asp-for="Id"/>

          <!--Nit-->
          <div class="mb-3">
            <label asp-for="Nit" class="form-label">Nit</label>
            <input asp-for="Nit" type="text" class="form-control" />
            <span asp-validation-for="Nit" class="text-danger"></span>
          </div>

          <!--Nombre-->
          <div class="mb-3">
            <label asp-for="Name" class="form-label">Nombre</label>
            <input asp-for="Name" type="text" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
          </div>

          <!--Direccion-->
          <div class="mb-3">
            <label asp-for="Direccion" class="form-label">Direccion</label>
            <input asp-for="Direccion" type="text" class="form-control" />
            <span asp-validation-for="Direccion" class="text-danger"></span>
          </div>

          <div class="container">
            <div class="col-sm">
                <input type="submit" value="Actualizar" class="btn btn-primary" />
            </div>
          </div>
      </form>
    </div>
</div>

Actividades/Actividad7/Actividad7/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Proyecto Final Crud</h1>
</div>

Actividades/Actividad7/Actividad7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Actividad7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Actividad7.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Actividad7</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enterprise" asp-action="Index">Empresas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Actividad7 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>